services:
  api:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports: ["3001:3001"]
    volumes:
      - ./backend:/app
  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/app
    depends_on:
      - api
